// 봇 계정으로 글/댓글을 작성할 때 공통으로 쓰는 가짜 프로필 풀.

import 'dart:math';

typedef BotProfile = ({String nickname, int level});

const List<BotProfile> botProfiles = [
  (nickname: '오늘도맑음', level: 4),
  (nickname: '소소한하루', level: 5),
  (nickname: '커피한잔', level: 6),
  (nickname: '밤산책', level: 3),
  (nickname: '느긋한사람', level: 7),
  (nickname: '초코라떼', level: 5),
  (nickname: '파란노트', level: 4),
  (nickname: '하루기록', level: 8),
  (nickname: '조용한방', level: 6),
  (nickname: '민트초코', level: 3),
  (nickname: '구름위로', level: 5),
  (nickname: '작은습관', level: 7),
  (nickname: '동네친구', level: 4),
  (nickname: '새벽감성', level: 6),
  (nickname: '읽는사람', level: 8),
  (nickname: '기록중', level: 5),
  (nickname: '단팥빵', level: 3),
  (nickname: '노을빛', level: 6),
  (nickname: '심심한날', level: 4),
  (nickname: '바람소리', level: 7),
  (nickname: '두부멘탈', level: 5),
  (nickname: '느린거북', level: 3),
  (nickname: '아침햇살', level: 8),
  (nickname: '잠깐들림', level: 4),
  (nickname: '라면먹자', level: 6),
  (nickname: '고요한밤', level: 7),
  (nickname: '낮잠필요', level: 5),
  (nickname: '물한잔', level: 3),
  (nickname: '먼지없는날', level: 6),
  (nickname: '흰운동화', level: 4),
  (nickname: '달달한거', level: 8),
  (nickname: '노트정리', level: 5),
  (nickname: '어쩌다보니', level: 7),
  (nickname: '그냥웃자', level: 4),
  (nickname: '버터토스트', level: 6),
  (nickname: '청량한밤', level: 3),
  (nickname: '고민중', level: 5),
  (nickname: '천천히가자', level: 8),
  (nickname: '작은방', level: 4),
  (nickname: '여름비', level: 6),
  (nickname: '메모장', level: 7),
  (nickname: '대충살자', level: 5),
  (nickname: '반짝이는중', level: 3),
  (nickname: '오늘뭐하지', level: 6),
  (nickname: '혼잣말', level: 4),
  (nickname: '따뜻한물', level: 8),
  (nickname: '가벼운마음', level: 5),
  (nickname: '문득생각', level: 7),
  (nickname: '책상정리', level: 4),
  (nickname: '느낌표', level: 6),
  // ─── 커뮤/주식 커뮤 감성 닉네임 ───
  (nickname: '존버는승리한다', level: 9),
  (nickname: '풀매수가즈아', level: 6),
  (nickname: '물타기장인', level: 5),
  (nickname: '익절은과학', level: 8),
  (nickname: '손절은예술', level: 4),
  (nickname: '상한가가자', level: 7),
  (nickname: '떡상기원', level: 5),
  (nickname: '내일은오른다', level: 6),
  (nickname: '계좌녹는중', level: 3),
  (nickname: '존버맨', level: 7),
  (nickname: '개미는오늘도', level: 5),
  (nickname: '불기둥기다림', level: 6),
  (nickname: '추매각', level: 4),
  (nickname: '단타치다죽음', level: 5),
  (nickname: '눈물의손절', level: 3),
  (nickname: '곱버스탑승', level: 6),
  (nickname: '영끌막차', level: 4),
  (nickname: '존버3년차', level: 9),
  (nickname: '담보비상', level: 5),
  (nickname: '반대매매당함', level: 3),
  (nickname: '그래서언제올라', level: 6),
  (nickname: '내가사면떨어짐', level: 4),
  (nickname: '내가팔면오름', level: 5),
  (nickname: '물렸다', level: 3),
  (nickname: '존버존버', level: 7),
  (nickname: '익절후폭등', level: 6),
  (nickname: '한강뷰가는중', level: 3),
  (nickname: '떡락방지위원', level: 5),
  (nickname: '천슬라가즈아', level: 8),
  (nickname: '서학개미', level: 7),
  (nickname: '동학개미운동', level: 6),
  (nickname: '풀시드박았다', level: 5),
  (nickname: '오늘도파란불', level: 4),
  (nickname: '빨간날이좋아', level: 6),
  (nickname: '존버는승리', level: 8),
  (nickname: '주린이탈출', level: 4),
  (nickname: '차트보는남자', level: 7),
  (nickname: '봉투기다림', level: 5),
  (nickname: '관망중', level: 6),
  (nickname: '눈팅족', level: 4),
  (nickname: '댓글만쓰는사람', level: 5),
  (nickname: '커뮤폐인', level: 6),
  (nickname: '새벽에깨어있음', level: 7),
  (nickname: '오늘도손가락', level: 4),
  (nickname: '광클하는중', level: 5),
  (nickname: '도파민중독', level: 6),
  (nickname: '알람노예', level: 3),
  (nickname: '월급증발', level: 5),
  (nickname: '치킨값벌자', level: 4),
  (nickname: '소액주주연대', level: 7),
];

/// Firebase uid 형식(28자 영숫자)처럼 보이는 가짜 uid 생성
String generateFakeBotUid() {
  const chars =
      'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  // 웹(JS)에서는 64비트 정수 연산이 정확하지 않으므로 Random 으로 대체.
  // 원래도 now() 시드 기반 비결정적 값이라 동작상 차이 없음.
  final rng = Random();
  final buf = StringBuffer();
  for (var i = 0; i < 28; i++) {
    buf.write(chars[rng.nextInt(chars.length)]);
  }
  return buf.toString();
}
